config/routes.rb
HackerNews::Application.routes.draw do
  root to: "links#index"

  resources :links do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :link
end

app/models/link.rb
require 'time'
require 'date'

class Link < ActiveRecord::Base
  has_many :comments

  validates :title, :presence => true
  validates :url, :presence => true

  before_save :prefix_url

  def self.order_by_score
    Link.order(:score => :desc)
  end

  def modified_score
    time = Time.new
    age = ((time - self.created_at)/60/60/24).to_i
    modified_score = score + age * (-0.5)
    modified_score
  end

  def self.order_by_modified_score
    links = Link.all
    modified_links = {}
    links.each do |link|
      modified_links[link] = link.modified_score
    end
    new_order = modified_links.keys.sort {|a, b| modified_links[b] <=> modified_links[a]}
  end

  def age
    time = Time.new
    age = time - self.created_at


    result = ''
    if age < (60*60)
      result = "#{(age/60).to_i} minutes"
    elsif age < (60*60*24)
      result = "#{(age/60/60).to_i} hours"
    else
      result = "#{(age/60/60/24).to_i} days"
    end
    result
  end

  private

  def prefix_url
    regex = /http/
    unless self.url.match(regex)
      self.url = "http://#{self.url}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @link = Link.find(params[:link_id])
  end

  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "Your comment has been saved."
      redirect_to link_path(@link)
    else
      render 'new'
    end
  end

  def edit
    @link = Link.find(params[:link_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @link = Link.find(params[:link_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:notice] = "Your comment was updated."
      redirect_to link_path(@link)
    else
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = "Your comment was deleted."
    redirect_to :back
  end

  private
  def comment_params
    params.require(:comment).permit(:description, :link_id)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.order_by_modified_score
  end

  def show
    @link = Link.find(params[:id])
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.create(link_params)
    if @link.save
      @link.update(:score => 0)
      flash[:notice] = "#{@link.title} has been added"
      redirect_to links_path
    else
      render 'links/new.html.erb'
    end
  end

  def update
    @link = Link.find(params[:id])
    @link.update(link_params)
    redirect_to links_path
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to links_path
  end

  private
  def link_params
    params.require(:link).permit(:title, :url, :score)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render('layouts/error', :object => @comment) %>

<%= form_for [@link, @comment] do |f| %>
  <div class = "form-group">
    <%= f.text_area :description %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/comments/edit.html.erb
<h1><%= @link.title %></h1>

<h3>Edit your comment</h3>

<%= render 'form' %>

app/views/comments/new.html.erb
<h1><%= @link.title %></h1>

<h3>Add your comment</h3>

<%= render 'form' %>

app/views/layouts/_error.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNews</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lusitana' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>
</head>
<body>
<div id="wrapper">
  <nav>
    <%= link_to 'Home', :root %> |
    <%= link_to 'New', links_path %> |
    <%= link_to 'Comments', links_path %> |
    <%= link_to 'Submit', new_link_path %>
  </nav>
  <h2><%= flash[:notice] %></h2>
  <%= yield %>
</div>
</body>
</html>

app/views/links/_form.html.erb
<%= render('layouts/error', :object => @link) %>

<%= form_for(@link) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/links/index.html.erb
<h1>Hacker News</h1>

<ol>
  <% @links.each do |link| %>
    <li>
      <%= link_to "↑", link_path(link, "link[score]" => (link.score.to_i + 1)), :method => :patch %>
      <a href="<%=link.url%>"><%= link.title %> </a>
      (<%=link.url%>)
    </li>
    <p class='title_info'> <%=link.score.to_i%> points. | <%= link_to "#{link.comments.length} comments", link_path(link) %> | Created <%=link.age%> ago  | <%= link_to "delete", link_path(link), :method => 'delete' %>  </p>
  <% end %>
</ol>

<%= link_to "Add a new link", new_link_path, :class=> "btn btn-default" %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render('form') %>

app/views/links/show.html.erb
<h1><%=@link.title %></h1>


<% @link.comments.each do |comment| %>
  <br>
  <div class="comment">
    <p><%= comment.description %></p>
    <p><%= link_to "Edit", edit_link_comment_path(@link, comment), :class => "comment-link" %> |
      <%= link_to "Delete", link_comment_path(@link, comment), :method => 'delete', :class => 'comment-link' %></p>
  </div>
  <br>
<% end %>

<%= link_to "Add a comment", new_link_comment_path(@link), :class => "btn btn-default" %>